name: 🔨 Checking Sonar quality
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm i
      - name: Unit-testing
        run: npm run test-with-cov
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
