name: Checking pagespeed insight
on:
  push:
    branches:
      - main
jobs:
  pagespeed:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
    - name: Pagespeed
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.pagespeed.screenshot.svg
        token: NOT_NEEDED
        base: ""
        plugin_pagespeed: yes
        plugin_pagespeed_screenshot: yes
        plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
        plugin_pagespeed_url: https://ildan-dev.ru